name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Unit Tests & Example Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements-dev.txt

      - name: Run Unit Tests & Examples
        run: python tests/tests.py
